apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: config
        ports:
        - containerPort: 8888
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: config
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    app: config
  type: LoadBalancer
