config:
  image: imich/config-server:v1
  ports:
    - 8888:8888

eureka:
  image: imich/eureka:v1
  ports:
    - 8761:8761
  links:
    - config

employee:
  image: imich/employee:v1
  ports:
    - 8011:8011
  links:
    - config
    - eureka
