version: '2'

services:
  config:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - 8888:8888

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    links:
      - config

  employee:
    build:
      context: ./employee
      dockerfile: Dockerfile
    ports:
      - 8011:8011
    links:
      - config
      - eureka

  basicexample:
    build:
      context: ./basicexample
      dockerfile: Dockerfile
    ports:
      - 8012:8012
    links:
      - config
      - eureka

  basicclient:
    build:
      context: ./clientexample
      dockerfile: Dockerfile
    ports:
      - 8015:8015
    links:
      - config
      - eureka
      - basicexample


  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - 8065:8065
    links:
      - config
      - eureka

  auth-apigateway:
    build:
      context: ./auth-apigateway
      dockerfile: Dockerfile
    environment:
      user: default
      password: default
      port: 33060
    ports:
      - 8066:8066
    links:
      - config
      - eureka
      - mysqlhost

  mysqlhost:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: com
      MYSQL_USER: default
      MYSQL_PASSWORD: default
    ports:
     - 33060:3306
    volumes:
      - "./setting/db:/docker-entrypoint-initdb.d"
