INSERT INTO oauth_client_details (CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, WEB_SERVER_REDIRECT_URI, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY, ADDITIONAL_INFORMATION, AUTOAPPROVE) VALUES ('foo2', '', 'bar2', 'read', 'password,authorization_code,refresh_token', '', '', null, null, '{}',null);



INSERT INTO oauth_client_details (CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, WEB_SERVER_REDIRECT_URI, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY, ADDITIONAL_INFORMATION, AUTOAPPROVE) VALUES ('f1843165-de93-41a8-81c4-d56fbb82dba0', '', 'ae2fef54-0d50-4252-b585-ae6f0f035b4d', 'read', 'password,authorization_code,refresh_token', '', '', null, null, '{}',null);
